#!/usr/bin/python3 -u

import argparse
import shlex
import sys
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument('command', nargs='+')
args = parser.parse_args()

while True:
    try:
        uargs = shlex.split(input(' '.join(args.command) + '>> '))
    except EOFError:
        sys.exit(0)
    except ValueError as e:
        print(e)
        continue

    subprocess.call(args.command + uargs)
